

name: ALL

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app-name: [ 'test' ]
        s3-bucket: [ 'tertertert-sorce' ]
        deploy-group: [ 'test-group' ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      # Creating deployment via CodeDeploy
      #       Deploy push to S3
      - name: Deploy build scripts on AWS
        run: |
          aws deploy push \
          --application-name ${{ matrix.app-name }} \
          --ignore-hidden-files \
          --s3-location s3://${{ matrix.s3-bucket }}/all.zip \
          --source ./build-scripts/all
      - name: Creating AWS Deployment
        run: |
          aws deploy create-deployment \
          --application-name ${{ matrix.app-name }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{ matrix.deploy-group }} \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=${{ matrix.s3-bucket }},key=all.zip,bundleType=zip \
